### ISSUE TITLE
Compiling the UnityInterface.cpp

### ISSUE THREAD

**Issue by ashokbugude** [rfilkov/OpenNi2UnityInterface#1]
Hi,

To run OpenNi2 using Unity . I need to compile  UnityInterface.cpp right ?
I tried to compile UnityInterface.cpp , but its dependent on OpenNI.h, NiTE.h etc  which in turn dpends on many other files. Is there any location where all the required files for compiling UnityInterface.cpp ?

**Comment by rfilkov** [comment]
The only files to compile are UnityInterface.cpp & UnityInterface.h. Of course, they reference the header files of OpenNI2 and NiTE2, because later the respective libraries will be needed. You should add the Include- & Lib-subdirectories of these packages to the paths used for compilation and linking. If you want them all in one location, just copy them from directories where these packages were installed (or unzipped) on your machine.

**Comment by ashokbugude** [comment]
Hi I have added all the needed files in compilation path and tried to compile. But I get below errors, Am I making any mistake ?

In file included from UnityInterface.cpp:1:0:
UnityInterface.h:21:25: error: expected ‘)’ before ‘*’ token
 typedef void (__stdcall \* pfn_user_callback)(int nUserId);
                         ^
In file included from UnityInterface.cpp:1:0:
UnityInterface.h:54:46: error: variable or field ‘StartLookingForUsers’ declared void
 UNITYINTERFACE_API void StartLookingForUsers(pfn_user_callback pNewUser, pfn_us
                                              ^
UnityInterface.h:54:46: error: ‘pfn_user_callback’ was not declared in this scope

**Comment by rfilkov** [comment]
UNITYINTERFACE_API is a macro used to declare the functions as exported on the different OS. These will be the functions that will be called later by the C# scripts. I'm not sure how this should be declared on Linux. Research a bit.

**Comment by ashokbugude** [comment]
Hi Thanks for your help. 
I am able to resolve the above issues by modifying 'typedef void (__stdcall \* pfn_user_callback)(int nUserId);' to 'typedef void (\* pfn_user_callback)(int nUserId);'   at line 21 of UnityInterface.h . 

Sorry for bugging you
I am unable to resolve the new set of errors (undefined reference errors) generated as shown below

ashok@ashok:~/Downloads/OpenNi2UnityInterface-master$ g++ UnityInterface.cpp
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to`main'
/tmp/ccryXv6c.o: In function `openni::VideoFrameRef::release()':
UnityInterface.cpp:(.text._ZN6openni13VideoFrameRef7releaseEv[_ZN6openni13VideoFrameRef7releaseEv]+0x23): undefined reference to`oniFrameRelease'
/tmp/ccryXv6c.o: In function `openni::VideoFrameRef::_setFrame(OniFrame*)':
UnityInterface.cpp:(.text._ZN6openni13VideoFrameRef9_setFrameEP8OniFrame[_ZN6openni13VideoFrameRef9_setFrameEP8OniFrame]+0x32): undefined reference to`oniFrameAddRef'
/tmp/ccryXv6c.o: In function `openni::VideoStream::start()':
UnityInterface.cpp:(.text._ZN6openni11VideoStream5startEv[_ZN6openni11VideoStream5startEv]+0x31): undefined reference to`oniStreamStart'
/tmp/ccryXv6c.o: In function `openni::VideoStream::stop()':
UnityInterface.cpp:(.text._ZN6openni11VideoStream4stopEv[_ZN6openni11VideoStream4stopEv]+0x2a): undefined reference to`oniStreamStop'
/tmp/ccryXv6c.o: In function `openni::VideoStream::readFrame(openni::VideoFrameRef*)':
UnityInterface.cpp:(.text._ZN6openni11VideoStream9readFrameEPNS_13VideoFrameRefE[_ZN6openni11VideoStream9readFrameEPNS_13VideoFrameRefE]+0x4b): undefined reference to`oniStreamReadFrame'
/tmp/ccryXv6c.o: In function `openni::VideoStream::getProperty(int, void*, int*) const':
UnityInterface.cpp:(.text._ZNK6openni11VideoStream11getPropertyEiPvPi[_ZNK6openni11VideoStream11getPropertyEiPvPi]+0x47): undefined reference to`oniStreamGetProperty'
/tmp/ccryXv6c.o: In function `openni::VideoStream::isPropertySupported(int) const':
UnityInterface.cpp:(.text._ZNK6openni11VideoStream19isPropertySupportedEi[_ZNK6openni11VideoStream19isPropertySupportedEi]+0x39): undefined reference to`oniStreamIsPropertySupported'
/tmp/ccryXv6c.o: In function `openni::VideoStream::_setHandle(_OniStream*)':
UnityInterface.cpp:(.text._ZN6openni11VideoStream10_setHandleEP10_OniStream[_ZN6openni11VideoStream10_setHandleEP10_OniStream]+0x42): undefined reference to`oniStreamGetSensorInfo'
/tmp/ccryXv6c.o: In function `openni::Device::getSensorInfo(openni::SensorType)':
UnityInterface.cpp:(.text._ZN6openni6Device13getSensorInfoENS_10SensorTypeE[_ZN6openni6Device13getSensorInfoENS_10SensorTypeE]+0xd3): undefined reference to`oniDeviceGetSensorInfo'
/tmp/ccryXv6c.o: In function `openni::Device::isPropertySupported(int) const':
UnityInterface.cpp:(.text._ZNK6openni6Device19isPropertySupportedEi[_ZNK6openni6Device19isPropertySupportedEi]+0x20): undefined reference to`oniDeviceIsPropertySupported'
/tmp/ccryXv6c.o: In function `openni::Device::isCommandSupported(int) const':
UnityInterface.cpp:(.text._ZNK6openni6Device18isCommandSupportedEi[_ZNK6openni6Device18isCommandSupportedEi]+0x20): undefined reference to`oniDeviceIsCommandSupported'
/tmp/ccryXv6c.o: In function `openni::Device::_setHandle(_OniDevice*)':
UnityInterface.cpp:(.text._ZN6openni6Device10_setHandleEP10_OniDevice[_ZN6openni6Device10_setHandleEP10_OniDevice]+0x4c): undefined reference to`oniDeviceGetInfo'
/tmp/ccryXv6c.o: In function `openni::OpenNI::initialize()':
UnityInterface.cpp:(.text._ZN6openni6OpenNI10initializeEv[_ZN6openni6OpenNI10initializeEv]+0xa): undefined reference to`oniInitialize'
/tmp/ccryXv6c.o: In function `openni::OpenNI::shutdown()':
UnityInterface.cpp:(.text._ZN6openni6OpenNI8shutdownEv[_ZN6openni6OpenNI8shutdownEv]+0x5): undefined reference to`oniShutdown'
/tmp/ccryXv6c.o: In function `openni::OpenNI::getExtendedError()':
UnityInterface.cpp:(.text._ZN6openni6OpenNI16getExtendedErrorEv[_ZN6openni6OpenNI16getExtendedErrorEv]+0x5): undefined reference to`oniGetExtendedError'
/tmp/ccryXv6c.o: In function `openni::OpenNI::enumerateDevices(openni::Array<openni::DeviceInfo>*)':
UnityInterface.cpp:(.text._ZN6openni6OpenNI16enumerateDevicesEPNS_5ArrayINS_10DeviceInfoEEE[_ZN6openni6OpenNI16enumerateDevicesEPNS_5ArrayINS_10DeviceInfoEEE]+0x2a): undefined reference to`oniGetDeviceList'
UnityInterface.cpp:(.text._ZN6openni6OpenNI16enumerateDevicesEPNS_5ArrayINS_10DeviceInfoEEE[_ZN6openni6OpenNI16enumerateDevicesEPNS_5ArrayINS_10DeviceInfoEEE]+0x4e): undefined reference to `oniReleaseDeviceList'
/tmp/ccryXv6c.o: In function`openni::OpenNI::waitForAnyStream(openni::VideoStream*_, int, int_, int)':
UnityInterface.cpp:(.text._ZN6openni6OpenNI16waitForAnyStreamEPPNS_11VideoStreamEiPii[_ZN6openni6OpenNI16waitForAnyStreamEPPNS_11VideoStreamEiPii]+0x122): undefined reference to `oniWaitForAnyStream'
/tmp/ccryXv6c.o: In function`openni::CoordinateConverter::convertWorldToDepth(openni::VideoStream const&, float, float, float, int_, int_, unsigned short*)':
UnityInterface.cpp:(.text._ZN6openni19CoordinateConverter19convertWorldToDepthERKNS_11VideoStreamEfffPiS4_Pt[_ZN6openni19CoordinateConverter19convertWorldToDepthERKNS_11VideoStreamEfffPiS4_Pt]+0x6d): undefined reference to `oniCoordinateConverterWorldToDepth'
